### ISSUE TITLE
Data not accessible 

### ISSUE THREAD

**Issue by ericotjo001** [evandez/neuron-descriptions#1]
Hi Evan, it seems like the data are still not accessible. Look forward to the update, thanks!

**Comment by evandez** [comment]
Can you please provide more information about what failed?

I may have just fixed the problem: the links in the README were https, not http.

**Comment by ericotjo001** [comment]
Hi yes, it works now. I can save the zip files directly. Thanks!

Previously it simply led me to milan.csail.mit.edu/data/<thezip> which gave 404.
