### ISSUE TITLE
erro on compute_milan_descriptions.py

### ISSUE THREAD

**Issue by Fatemeh490** [evandez/neuron-descriptions#12]
I faced an error when computing Milan descriptions with running code below:
`! python3 -m scripts.compute_milan_descriptions biggan imagenet --device cuda`

 the error is located on line 71 of compute_milan_descriptions.py. 
`with results_csv_file.open('r') as handle:`
I think it should be:
`with results_csv_file.open('w') as handle:`

**Comment by evandez** [comment]
Good catch, fixed!
