### ISSUE TITLE
ImageNet validation set selection

### ISSUE THREAD

**Issue by SinHanYang** [evandez/neuron-descriptions#13]
Dear Evan Hernandez,

I tried to reproduce your code in the README/Downloading MILAN section.
I tried to execute 

`dataset = milannotations.load('alexnet/imagenet')`

,which need to download ImageNet source images.
I downloaded ILSVRC2012 validation set, and make images into 1000 class folders. Finally, I put them in MILAN_DATA_DIR.
However, when I executed to code, it show errors:

`
Traceback (most recent call last):
  File "reproduce.py", line 7, in <module>
    dataset = milannotations.load('alexnet/imagenet')
  File "/home/shyang/neuron-descriptions/src/milannotations/loaders.py", line 250, in load
    dataset = dataset_hub.load(name, **kwargs)
  File "/home/shyang/neuron-descriptions/src/utils/hubs.py", line 286, in load
    dataset = config.load(path=path, **kwargs)
  File "/home/shyang/neuron-descriptions/src/utils/hubs.py", line 251, in load
    return factory(path, **kwargs)
  File "/home/shyang/neuron-descriptions/src/milannotations/merges.py", line 225, in maybe_merge_and_load_dataset
    merge(root, source_dataset, force=force, image_index=image_index)
  File "/home/shyang/neuron-descriptions/src/milannotations/merges.py", line 157, in merge
    renormalizer(torch.stack(images_by_unit)).byte())
  File "/home/shyang/neuron-descriptions/src/deps/netdissect/renormalize.py", line 136, in __call__
    result = data.mul(mul).add_(add)
RuntimeError: The size of tensor a (224) must match the size of tensor b (3) at non-singleton dimension 4
`

I guess images of size 224*224 aren't suitable to your code. Which validation set should I download in order to execute 

`dataset = milannotations.load('alexnet/imagenet')`

Thanks

**Comment by yeongjoonJu** [comment]
I also had the same error.

**Comment by yeongjoonJu** [comment]
I also had the same error.

I resolved the error by modifying "src/netdissect/renormalize.py" as follows:

**Original**
```
def __call__(self, data):
        mul, add = [d.to(data.device, data.dtype) for d in [self.mul, self.add]]
        if data.ndimension() == 3:
            mul, add = [d[:, None, None] for d in [mul, add]]
        elif data.ndimension() == 4:
            mul, add = [d[None, :, None, None] for d in [mul, add]]
```

**Modified**
```
def __call__(self, data):
        mul, add = [d.to(data.device, data.dtype) for d in [self.mul, self.add]]
        if data.ndimension() == 3:
            mul, add = [d[:, None, None] for d in [mul, add]]
        elif data.ndimension() == 4:
            mul, add = [d[None, :, None, None] for d in [mul, add]]
        elif data.ndimension() == 5:
            mul, add = [d[None, None, :, None, None] for d in [mul, add]]
```

However, another errors are raised the followings:
```
merging source images (layer blocks.5.mlp.fc1): 100%|████████████████████| 12/12 [01:41<00:00,  8.48s/it]
load dino_vits8/imagenet:   0%|                                                   | 0/12 [00:00<?, ?it/s]
/workspace/neuron-descriptions/data/dino_vits8/imagenet/blocks.0.mlp.fc1/images.npy
torch.Size([100, 15, 3, 224, 224]) torch.Size([100, 15, 1, 224, 224])
load dino_vits8/imagenet:   8%|███▌                                       | 1/12 [00:00<00:05,  2.03it/s]
/workspace/neuron-descriptions/data/dino_vits8/imagenet/blocks.1.mlp.fc1/images.npy
torch.Size([100, 15, 3, 224, 224]) torch.Size([100, 15, 1, 224, 224])
load dino_vits8/imagenet:  17%|███████▏                                   | 2/12 [00:00<00:04,  2.08it/s]
/workspace/neuron-descriptions/data/dino_vits8/imagenet/blocks.10.mlp.fc1/images.npy
torch.Size([1500, 3, 224, 224]) torch.Size([100, 15, 1, 224, 224])
load dino_vits8/imagenet:  17%|███████▏                                   | 2/12 [00:01<00:05,  1.82it/s]
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    dataset = milannotations.load('dino_vits8/imagenet')
  File "/workspace/neuron-descriptions/src/milannotations/loaders.py", line 250, in load
    dataset = dataset_hub.load(name, **kwargs)
  File "/workspace/neuron-descriptions/src/utils/hubs.py", line 286, in load
    dataset = config.load(path=path, **kwargs)
  File "/workspace/neuron-descriptions/src/utils/hubs.py", line 251, in load
    return factory(path, **kwargs)
  File "/workspace/neuron-descriptions/src/milannotations/merges.py", line 226, in maybe_merge_and_load_dataset
    else:
  File "/workspace/neuron-descriptions/src/milannotations/datasets.py", line 405, in __init__
    top_images_dataset = TopImagesDataset(root, *args, **kwargs)
  File "/workspace/neuron-descriptions/src/milannotations/datasets.py", line 172, in __init__
    raise ValueError(f'expected 5D {name}, '
ValueError: expected 5D images, got 4D in layer blocks.10.mlp.fc1
```
I am trying to fix the error with minimal modifications.

**Comment by evandez** [comment]
Thanks for raising this issue, and sorry for the delay, I've been away for a bit. This was due to an issue of `renormalizer` being applied to a 5D image array instead of a 4D one. Should be fixed on master now, but let me know if this persists.
