### ISSUE TITLE
File to change root

### ISSUE THREAD

**Issue by meghalD** [evandez/neuron-descriptions#14]
I am unable to find any documentation about the file where we can change the following variables :

MILAN_DATA_DIR=./data
MILAN_MODELS_DIR=./models
MILAN_RESULTS_DIR=./results

**Comment by evandez** [comment]
Sorry for the delay, I've been away all summer.

These are environment variables. You can set those variables to e.g. your `.bashrc`. Or you can edit the default in `src/utils/env.py`.
