### ISSUE TITLE
[Question] Is validation set or train dataset used for generating exemplars?

### ISSUE THREAD

**Issue by somil55** [evandez/neuron-descriptions#19]

**Comment by evandez** [comment]
Validation dataset! Better to use inputs the model has not been directly trained on.

**Comment by somil55** [comment]
Thanks! Can you please fix the typos in script Ln12 : https://github.com/evandez/neuron-descriptions/blob/main/scripts/compute_exemplars.py. The definition of dataset here in Line 12 is “dataset model is trained on”.

**Comment by evandez** [comment]
done
