### ISSUE TITLE
ImageNet Folder Structure

### ISSUE THREAD

**Issue by ericotjo001** [evandez/neuron-descriptions#2]
Hi, 

Could you provide a hierarchy of your imagenet data folders?

I copied the test/train/val folders from the original ILSVRC/Data/CLS-LOC into the following:

neuron-descriptions/data/imagenet/train
neuron-descriptions/data/imagenet/test
neuron-descriptions/data/imagenet/val

and get the following error following minimal example in the README.

  File "/home/ericotjoaubu/Documents/GitHub/neuron-descriptions/env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 221, in find_classes
    return find_classes(directory)
  File "/home/ericotjoaubu/Documents/GitHub/neuron-descriptions/env/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in /home/ericotjoaubu/Documents/GitHub/neuron-descriptions/data/imagenet/val.

**Comment by evandez** [comment]
Hi Erico, I guess I'm not sure how the source is formatted these days. On our cluster, it's laid out like:

imagenet/
  train/
    ...
  val/
    class_id_1/
       some_image.jpeg
       some_other_image.jpeg
    class_id_2/
      ...

In other words, it works out of the box with ImageFolder. How is your val directory laid out?

**Comment by ericotjo001** [comment]
Thanks, I will make a pull request that adds an intermediate code that rearranges the data (based on my arrangement) if the user encounters this problem.

But before that, I encountered another problem in the minimal example at the very end. My minimal code is the following after a small edit (don't worry about the extra dargs, I will explain during the pull request):

    dataset = milannotations.load('dino_vits8/imagenet',**dargs) ; print('dataset loaded...')    
    sample = dataset.lookup(dargs['lookup_layer'], dargs['lookup_unit'])

    # Caption the top images.
    print(sample.images[None].shape, sample.masks[None].shape) # torch.Size([1, 15, 3, 224, 224]) torch.Size([1, 15, 1, 224, 224])

    outputs = milan(sample.images[None], masks=sample.masks[None])
    print(outputs.captions[0])

I believe sample images and masks have been computed normally (see the printed shapes), but when milan is called as per your README example, I got 

File "/home/ericotjoaubu/Documents/GitHub/neuron-descriptions/srcEt/tutorials.py", line 32, in runminimalexample
    outputs = milan(sample.images[None], masks=sample.masks[None])
TypeError: 'module' object is not callable

Am I missing something?

**Comment by monaGandhi09** [comment]
Hi Erico,

I encountered the same issue, could you share the code that you used to solve it? 
Thank you!

**Comment by ericotjo001** [comment]
Hello monaGandhi09, I submitted a pull request before. It was not approved at the time and I have closed it (since I'm not working on the project now). You can find the changes I made by navigating to that closed pull request or simply follow this link https://github.com/evandez/neuron-descriptions/pull/3/files.

**Comment by monaGandhi09** [comment]
Thanks a lot!
