### ISSUE TITLE
The activation map for fully-connected neurons in DINO

### ISSUE THREAD

**Issue by BierOne** [evandez/neuron-descriptions#22]
Hi, @evandez! Thanks for this outstanding work. I really appreciate your public code.

In Figure 2 and 12 of your paper, there are many activation maps for the FC layer in DINO. Could you please share more details about this generation process? Thanks a lot.

**Comment by evandez** [comment]
Sure thing. The process for getting those high-activation masks looks very similar to convolutional networks. The only difference is the ViT carves the image up into patches, so we get one MLP neuron activation per patch, and we threshold over those patches.

You can see how the ViT MLP features are spatialized here:
https://github.com/evandez/neuron-descriptions/blob/main/src/exemplars/transforms.py#L54

I'm not sure if this answers your question, but let me know if I can clarify further.

**Comment by BierOne** [comment]
Thank you for this prompt reply! It solves my question nicely!
