### ISSUE TITLE
spatialize_vit_mlp should begin with index 1?

### ISSUE THREAD

**Issue by BierOne** [evandez/neuron-descriptions#23]
Hi! @evandez,

Thanks for this outstanding work. As shown in [DINO ViT](https://github.com/facebookresearch/dino/blob/main/vision_transformer.py#L214), it looks like that DINO utilizes the first token as the [CLS] (index 0). 

However, in your implementation of [spatialize_vit_mlp ](https://github.com/evandez/neuron-descriptions/blob/220cfb027cfdd04077946f744aeb0a2aa8c853f4/src/exemplars/transforms.py#L54), the [CLS] is excluded through **hiddens[:, :-1]**?  Should it be **hiddens[:, 1:]**?

**Comment by evandez** [comment]
Doh! I swear I checked that, but it looks like you're right. Likely this only slightly affects the visualizations, since the patches are fairly small. I will submit a fix and add an errata note somewhere.

Thanks for pointing it out!
