### ISSUE TITLE
Alexnet Places365 url is wrong?

### ISSUE THREAD

**Issue by FabienRoger** [evandez/neuron-descriptions#7]
The alexnet places365 model of which the link is given (http://pretorched-x.csail.mit.edu/models/alexnet_places365-0c3a7b83.pth) is an alexnet model that does not match the shapes announced (alexnet for places365 has conv layer of sizes 94, 256, 384, 384, 256, and the annotations match that) whereas the alexet weights in the links have shapes matching conv layer of sizes 64, 192, 384, 256, 256.

**Comment by evandez** [comment]
Sorry for the delay, was away all summer. Think this is fixed now!
